repos:
  - repo: local
    hooks:
      - id: oxlint
        name: oxlint
        entry: bunx oxlint -c ./oxlint.config.ts
        language: system
        files: \.(ts|tsx|js|jsx)$
        pass_filenames: true
      - id: oxfmt-check
        name: oxfmt-check
        entry: bunx oxfmt --check --ignore-path .gitignore --ignore-path .oxfmtignore
        language: system
        files: \.(ts|tsx|js|jsx|json)$
        pass_filenames: true
